### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by kassane** [kassane/qml_zig#2]
- [x] Windows (MinGW), it is necessary to rename the dotherside library using the prefix ".lib" over ".a" because the [zig prefers to follow the standard msvc prefix](https://github.com/ziglang/zig/issues/7799).
- [x] Linux a trouble happens under [qt.qpa.plugin](https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found).
- [x] MacOS it will be verified the break of the linkage. see [dotherside issue #43](https://github.com/filcuc/dotherside/issues/43)

**Comment by kassane** [comment]
At the moment the Zig compiler demonstrates incompatibility on the i686 architecture resulting in a  error during library linking.
Update: The environment is x86_64 and zig has compiled the x86_64 (target: native-windows-gnu :point_left: ) examples and the x86 library. :confused: 
### MSYS i686 (x86)

~~~bash
lld-link: error: undefined symbol: dos_qguiapplication_create
>>> referenced by C:\_\zig-cache\o\b6a92afc700a5d24fecee4afa2284abd\Animated.o:(.weak.main.default..refptr.__stack_chk_guard)

lld-link: error: undefined symbol: dos_qqmlapplicationengine_create
>>> referenced by C:\_\zig-cache\o\b6a92afc700a5d24fecee4afa2284abd\Animated.o:(.weak.main.default..refptr.__stack_chk_guard)

lld-link: error: undefined symbol: dos_qurl_create
>>> referenced by C:\_\zig-cache\o\b6a92afc700a5d24fecee4afa2284abd\Animated.o:(.weak.main.default..refptr.__stack_chk_guard)

lld-link: error: undefined symbol: dos_qqmlapplicationengine_load_url
>>> referenced by C:\_\zig-cache\o\b6a92afc700a5d24fecee4afa2284abd\Animated.o:(.weak.main.default..refptr.__stack_chk_guard)

lld-link: error: undefined symbol: dos_qguiapplication_exec
>>> referenced by C:\_\zig-cache\o\b6a92afc700a5d24fecee4afa2284abd\Animated.o:(.weak.main.default..refptr.__stack_chk_guard)

lld-link: error: undefined symbol: dos_qqmlapplicationengine_delete
>>> referenced by C:\_\zig-cache\o\b6a92afc700a5d24fecee4afa2284abd\Animated.o:(.weak.main.default..refptr.__stack_chk_guard)

lld-link: error: undefined symbol: dos_qguiapplication_quit
>>> referenced by C:\_\zig-cache\o\b6a92afc700a5d24fecee4afa2284abd\Animated.o:(.weak.main.default..refptr.__stack_chk_guard)
error: LLDReportedFailure
~~~

**Comment by kassane** [comment]
MSYS fixed!
https://github.com/kassane/qml_zig/blob/f5a48ee3fa7fecfe08ff14a07063b52ec2167d1f/.github/workflows/MSYS.yml#L39-L51

**Comment by kassane** [comment]
MacOS finally works! Thanks @kubkon

**Comment by kubkon** [comment]
> MacOS finally works! Thanks @kubkon

Anytime! If you bump into linker bugs, feel free to tag me in - I'll be more than happy to have a look!
