### ISSUE TITLE
Add a reference to the original author of this code. 

### ISSUE THREAD

**Issue by gbdlin** [kassane/qml_zig#5]
Almost all code in the `src` directory originates from https://github.com/vesim987/zqml, but the original author of this code wasn't mentioned anywhere. Please add proper mentions of the original author and adjust the license and the copyright marks in agreement with the original author.

**Comment by kassane** [comment]
Hi @gbdlin.

First, this project is an automatic generated wrapper, but the declared names are similar.
When he decided to carry out the project, he did not know about this other project made by @vesim987 and he did not object to the referencing by his code. Can refer to it, but still I am the author of this project.
